#pragma once

#include "NativeGameplayTags.h"

namespace TDGameplayTags
{
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Frozen)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_DamageCast)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Damage)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Status)
	TDGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Cooldown_Damage)
}
