"""시스템 Python으로 실행(언리얼 에디터 열림 필요): AnimationSources/Player의 검 공격 FBX를 SK_Mannequin에 60fps AnimSequence로 가져와 루트 모션을 켜고 DefaultSlot 몽타주(섹션 Attack·Recovery)를 만든다.
실행: python Tools/BlenderAnimation/import_sword_attack01.py [--name AS_TD_Player_SwordAttack01] [--recovery-frame 50] [--replace]  (PowerShell 권장, L-repo-01)
출력: /Game/Characters/Mannequins/Anims/Sword/<name>, AM_<name 접미>, Saved/BlenderAnimation/SwordAttack01/import-result.json
상태: 현행 (2026-09-25, --replace는 메타데이터 TDGeneratedBy가 이 도구인 에셋만 지운다)
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'Tools/AnimationAuthoring'))
from smoke_test import TDMcpAnimationClient  # noqa: E402

FOLDER = '/Game/Characters/Mannequins/Anims/Sword'
SKELETON = '/Game/Characters/Mannequins/Meshes/SK_Mannequin'
TOOL_TAG = 'Tools/BlenderAnimation/import_sword_attack01.py'
FPS = 60
WORK = ROOT / 'Saved/BlenderAnimation/SwordAttack01'


def run_in_editor(code, label):
    script_path = WORK / f'editor_{label}.py'
    script_path.write_text(code, encoding='utf-8')
    completed = subprocess.run([sys.executable, str(ROOT / 'Tools/run_in_editor.py'), str(script_path)], capture_output=True, text=True, cwd=ROOT, encoding='utf-8', errors='replace')
    lines = [line for line in completed.stdout.splitlines() if '[TDTool]' in line]
    if completed.returncode != 0:
        raise RuntimeError(f'{label} failed: {completed.stdout[-1500:]} {completed.stderr[-500:]}')
    return lines


def remove_previous(paths):
    code = (
        "import os, unreal\n"
        f"for path in {paths!r}:\n"
        "    if not unreal.EditorAssetLibrary.does_asset_exist(path):\n"
        "        continue\n"
        "    asset = unreal.EditorAssetLibrary.load_asset(path)\n"
        f"    if unreal.EditorAssetLibrary.get_metadata_tag(asset, 'TDGeneratedBy') != '{TOOL_TAG}':\n"
        "        raise RuntimeError(f'Refusing to delete {path}: not generated by this tool')\n"
        "    package = asset.get_outermost()\n"
        "    asset = None\n"
        "    unreal.EditorLoadingAndSavingUtils.unload_packages([package])\n"
        "    package = None\n"
        "    unreal.SystemLibrary.collect_garbage()\n"
        "    file_path = os.path.abspath(os.path.join(unreal.Paths.project_content_dir(), path[len('/Game/'):] + '.uasset'))\n"
        "    if os.path.exists(file_path):\n"
        "        os.remove(file_path)\n"
        "    unreal.log(f'[TDTool] deleted {path}')\n"
        f"unreal.AssetRegistryHelpers.get_asset_registry().scan_paths_synchronous(['{FOLDER}'], True)\n"
        f"for path in {paths!r}:\n"
        "    if unreal.EditorAssetLibrary.does_asset_exist(path):\n"
        "        raise RuntimeError(f'Still in editor memory after delete (restart the editor: python Tools/ue_editor.py restart): {path}')\n")
    return run_in_editor(code, 'remove_previous')


def configure_sequence(sequence_path):
    code = (
        "import unreal, json\n"
        f"sequence = unreal.EditorAssetLibrary.load_asset('{sequence_path}')\n"
        "sequence.set_editor_property('enable_root_motion', True)\n"
        "sequence.set_editor_property('root_motion_root_lock', unreal.RootMotionRootLock.REF_POSE)\n"
        "sequence.set_editor_property('force_root_lock', False)\n"
        f"unreal.EditorAssetLibrary.set_metadata_tag(sequence, 'TDGeneratedBy', '{TOOL_TAG}')\n"
        "saved = unreal.EditorAssetLibrary.save_loaded_asset(sequence, only_if_is_dirty=False)\n"
        "unreal.log('[TDTool] sequence ' + json.dumps({'root_motion': sequence.get_editor_property('enable_root_motion'), 'saved': saved,"
        " 'length': unreal.AnimationLibrary.get_sequence_length(sequence), 'frames': unreal.AnimationLibrary.get_num_frames(sequence)}))\n")
    return run_in_editor(code, 'configure_sequence')


def tag_montage(montage_path):
    code = (
        "import unreal\n"
        f"montage = unreal.EditorAssetLibrary.load_asset('{montage_path}')\n"
        f"unreal.EditorAssetLibrary.set_metadata_tag(montage, 'TDGeneratedBy', '{TOOL_TAG}')\n"
        "unreal.log('[TDTool] montage saved ' + str(unreal.EditorAssetLibrary.save_loaded_asset(montage, only_if_is_dirty=False)))\n")
    return run_in_editor(code, 'tag_montage')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--name', default='AS_TD_Player_SwordAttack01')
    parser.add_argument('--recovery-frame', type=int, default=50)
    parser.add_argument('--replace', action='store_true')
    args = parser.parse_args()
    WORK.mkdir(parents=True, exist_ok=True)
    sequence_path = f'{FOLDER}/{args.name}'
    montage_path = f'{FOLDER}/AM_{args.name[3:]}'
    result = {}
    if args.replace:
        result['removed'] = remove_previous([montage_path, sequence_path])
    client = TDMcpAnimationClient()
    result['sequence'] = client.call(
        '.TDBlenderAnimationTools.import_animation_fbx',
        source_file=str(ROOT / 'AnimationSources/Player' / f'{args.name}.fbx'),
        destination_folder=FOLDER, asset_name=args.name, skeleton_path=SKELETON,
        sample_rate=FPS, import_uniform_scale=1.0, preserve_local_transform=True)
    result['configure'] = configure_sequence(sequence_path)
    result['montage'] = client.request('.TDAnimationAuthoringTools.CreateMontage', {
        'asset_path': montage_path, 'slot': 'DefaultSlot', 'save': True, 'blend_in': 0.1, 'blend_out': 0.2,
        'segments': [{'sequence': sequence_path}],
        'sections': [{'name': 'Attack', 'time': 0}, {'name': 'Recovery', 'time': round((args.recovery_frame - 1) / FPS, 4)}]})
    if result['montage'].get('success'):
        result['montage_tag'] = tag_montage(montage_path)
    (WORK / 'import-result.json').write_text(json.dumps(result, indent=1, ensure_ascii=False), encoding='utf-8')
    print(json.dumps(result, ensure_ascii=False)[:3000])
    if not result['montage'].get('success'):
        raise SystemExit(1)


if __name__ == '__main__':
    main()
